name: "solana-playground"

x-client: &client
  platform: linux/amd64
  depends_on:
    wasm:
      condition: service_completed_successfully
    server:
      condition: service_started
  build:
    context: .
    dockerfile: ./client/Dockerfile
    args:
      HAS_SERVER: "true"
    additional_contexts:
      solana-playground-wasm: service:wasm
      solana-playground-server: service:server
  ports:
    - ${PG_CLIENT_PORT:-3000}:3000

services:
  wasm:
    platform: linux/amd64
    build:
      context: ./wasm

  server:
    platform: linux/amd64
    depends_on:
      - db
    build:
      context: ./server
    ports:
      - ${PG_PORT:-8080}:8080
    environment:
      - PG_DB_URI=mongodb://db:27017
      - PG_CLIENT_URL=http://localhost:${PG_CLIENT_PORT:-3000}
      - RUST_LOG=${RUST_LOG:-info}

  client:
    <<: *client
    profiles:
      - dev
    tty: true
    stdin_open: true

  client-prod:
    <<: *client
    profiles:
      - prod
    command: ["sh", "-c", "yarn build && npx serve -s build"]

  db:
    image: mongo:7
    volumes:
      - mongodb:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  mongodb:
