// DO NOT MANUALLY EDIT!
// This file has been generated by running `yarn generate-packages`.

import { PgServer } from "../server";
import type { OrString } from "../types";

/** All packages that are allowed to be used in JS code */
export type JsRuntimePackageName =
  | "@clockwork-xyz/sdk"
  | "@coral-xyz/anchor"
  | "@metaplex-foundation/js"
  | "@metaplex-foundation/mpl-bubblegum"
  | "@metaplex-foundation/mpl-token-metadata"
  | "@project-serum/anchor"
  | "@solana/buffer-layout"
  | "@solana/spl-account-compression"
  | "@solana/spl-token"
  | "@solana/spl-token-metadata"
  | "@solana/web3.js"
  | "assert"
  | "bn.js"
  | "borsh"
  | "buffer"
  | "mocha"
  | "solana-playground";

export class PgJsRuntimePackage {
  /**
   * Asynchronously import the given package.
   *
   * @param name package name
   * @returns the imported package
   */
  static async import(name: OrString<JsRuntimePackageName>) {
    if (process.env.NODE_ENV === "production") {
      switch (name) {
        case "@clockwork-xyz/sdk":
          return import("@clockwork-xyz/sdk");
        case "@coral-xyz/anchor":
          return import("@coral-xyz/anchor");
        case "@metaplex-foundation/js":
          return import("@metaplex-foundation/js");
        case "@metaplex-foundation/mpl-bubblegum":
          return import("@metaplex-foundation/mpl-bubblegum");
        case "@metaplex-foundation/mpl-token-metadata":
          return import("@metaplex-foundation/mpl-token-metadata");
        case "@project-serum/anchor":
          return import("@project-serum/anchor");
        case "@solana/buffer-layout":
          return import("@solana/buffer-layout");
        case "@solana/spl-account-compression":
          return import("@solana/spl-account-compression");
        case "@solana/spl-token":
          return import("@solana/spl-token");
        case "@solana/spl-token-metadata":
          return import("@solana/spl-token-metadata");
        case "@solana/web3.js":
          return import("@solana/web3.js");
        case "assert":
          return import("assert");
        case "bn.js":
          return import("bn.js");
        case "borsh":
          return import("borsh");
        case "buffer":
          return import("buffer");
        case "mocha":
          return import("mocha");
      }
    } else {
      const isImportable = PACKAGES.importable.some((n) => n === name);
      if (isImportable) return await PgServer.packages(name);
    }

    throw new Error(`Package \`${name}\` is not available.`);
  }
}
