export enum Emoji {
  CROSS = "❌ ",
  CHECKMARK = "✅ ",
  LOOKING_GLASS = "🔍 ",
  CANDY = "🍬 ",
  COMPUTER = "🖥 ",
  PAPER = "📝 ",
  CONFETTI = "🎉 ",
  PAYMENT = "💵 ",
  UPLOAD = "📤 ",
  WITHDRAW = "🏧 ",
  ASSETS = "🗂 ",
  LAUNCH = "🚀 ",
  COLLECTION = "📦 ",
  ERROR = "🛑 ",
  WARNING = "⚠️ ",
  SIGNING = "✍️ ",
  ICE_CUBE = "🧊 ",
  FIRE = "🔥 ",
  RIGHT_ARROW = "➡️ ",
  MONEY_BAG = "💰 ",
  SOL = "◎",
  GUARD = "🛡 ",
  WRAP = "📦 ",
  UNWRAP = "🔩 ",
}
