services:
  server:
    depends_on:
      - db
    build: .
    ports:
      - 8080:8080
    environment:
      - PG_DB_URI=postgresql://postgres:postgres@db:5432/solpg

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=solpg
    ports:
      - 5432:5432

volumes:
  postgres_data: