name: "solana-playground"
services:
  server:
    depends_on:
      - db
    build: .
    ports:
      - 8080:8080
    environment:
      - PG_DB_URI=mongodb://db:27017

  db:
    image: mongo:7
    volumes:
      - mongodb:/data/db
    # Override the default command because it logs a lot and setting `logging`
    # `driver` to `none` doesn't work
    command: mongod --quiet --logpath /dev/null

volumes:
  mongodb:
