import * as monaco from "monaco-editor";

export const loadMetaplexTypes = () => {
  /* ------------------ Begin @metaplex-foundation/js ------------------ */
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/old-index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/Metaplex.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/Metaplex.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/errors/BundlrError.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/errors/BundlrError.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/errors/MetaplexError.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/errors/MetaplexError.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/errors/ProgramError.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/errors/ProgramError.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/errors/ReadApiError.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/errors/ReadApiError.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/errors/RpcError.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/errors/RpcError.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/errors/SdkError.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/errors/SdkError.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/errors/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/errors/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/AuctionHouseBuildersClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/AuctionHouseBuildersClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/AuctionHouseClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/AuctionHouseClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/AuctionHousePdasClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/AuctionHousePdasClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/accounts.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/accounts.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/constants.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/constants.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/errors.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/errors.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/gpaBuilders/BidReceiptGpaBuilder.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/gpaBuilders/BidReceiptGpaBuilder.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/gpaBuilders/ListingReceiptGpaBuilder.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/gpaBuilders/ListingReceiptGpaBuilder.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/gpaBuilders/PurchaseReceiptGpaBuilder.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/gpaBuilders/PurchaseReceiptGpaBuilder.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/gpaBuilders/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/gpaBuilders/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/models/AuctionHouse.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/models/AuctionHouse.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/models/Bid.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/models/Bid.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/models/Listing.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/models/Listing.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/models/Purchase.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/models/Purchase.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/models/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/models/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/cancelBid.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/cancelBid.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/cancelListing.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/cancelListing.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/createAuctionHouse.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/createAuctionHouse.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/createBid.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/createBid.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/createListing.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/createListing.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/depositToBuyerAccount.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/depositToBuyerAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/directBuy.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/directBuy.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/directSell.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/directSell.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/executeSale.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/executeSale.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findAuctionHouseByAddress.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findAuctionHouseByAddress.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findAuctionHouseByCreatorAndMint.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findAuctionHouseByCreatorAndMint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findBidByReceipt.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findBidByReceipt.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findBidByTradeState.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findBidByTradeState.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findBids.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findBids.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findListingByReceipt.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findListingByReceipt.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findListingByTradeState.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findListingByTradeState.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findListings.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findListings.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findPurchaseByReceipt.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findPurchaseByReceipt.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findPurchaseByTradeState.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findPurchaseByTradeState.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findPurchases.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/findPurchases.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/getBuyerBalance.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/getBuyerBalance.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/loadBid.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/loadBid.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/loadListing.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/loadListing.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/loadPurchase.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/loadPurchase.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/updateAuctionHouse.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/updateAuctionHouse.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/withdrawFromBuyerAccount.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/withdrawFromBuyerAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/withdrawFromFeeAccount.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/withdrawFromFeeAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/withdrawFromTreasuryAccount.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/operations/withdrawFromTreasuryAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/auctionHouseModule/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/auctionHouseModule/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/bundlrStorage/BundlrStorageDriver.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/bundlrStorage/BundlrStorageDriver.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/bundlrStorage/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/bundlrStorage/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/bundlrStorage/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/bundlrStorage/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/CandyMachineBuildersClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/CandyMachineBuildersClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/CandyMachineClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/CandyMachineClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/CandyMachineGuardsClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/CandyMachineGuardsClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/CandyMachinePdasClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/CandyMachinePdasClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/asserts.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/asserts.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/constants.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/constants.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/errors.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/errors.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/addressGate.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/addressGate.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/allowList.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/allowList.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/botTax.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/botTax.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/core.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/core.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/default.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/default.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/endDate.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/endDate.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/freezeSolPayment.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/freezeSolPayment.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/freezeTokenPayment.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/freezeTokenPayment.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/gatekeeper.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/gatekeeper.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/mintLimit.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/mintLimit.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/nftBurn.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/nftBurn.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/nftGate.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/nftGate.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/nftPayment.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/nftPayment.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/programGate.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/programGate.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/redeemedAmount.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/redeemedAmount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/solPayment.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/solPayment.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/startDate.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/startDate.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/thirdPartySigner.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/thirdPartySigner.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/tokenBurn.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/tokenBurn.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/tokenGate.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/tokenGate.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/tokenPayment.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/guards/tokenPayment.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/models/CandyGuard.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/models/CandyGuard.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/models/CandyMachine.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/models/CandyMachine.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/models/CandyMachineHiddenSection.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/models/CandyMachineHiddenSection.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/models/CandyMachineItem.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/models/CandyMachineItem.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/models/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/models/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/callCandyGuardRoute.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/callCandyGuardRoute.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/createCandyGuard.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/createCandyGuard.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/createCandyMachine.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/createCandyMachine.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/deleteCandyGuard.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/deleteCandyGuard.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/deleteCandyMachine.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/deleteCandyMachine.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/findCandyGuardByAddress.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/findCandyGuardByAddress.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/findCandyGuardsByAuthority.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/findCandyGuardsByAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/findCandyMachineByAddress.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/findCandyMachineByAddress.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/insertCandyMachineItems.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/insertCandyMachineItems.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/mintFromCandyMachine.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/mintFromCandyMachine.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/unwrapCandyGuard.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/unwrapCandyGuard.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/updateCandyGuard.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/updateCandyGuard.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/updateCandyGuardAuthority.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/updateCandyGuardAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/updateCandyMachine.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/updateCandyMachine.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/wrapCandyGuard.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/operations/wrapCandyGuard.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineModule/programs.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineModule/programs.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/CandyMachinesV2BuildersClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/CandyMachinesV2BuildersClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/CandyMachinesV2Client.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/CandyMachinesV2Client.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/accounts.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/accounts.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/asserts.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/asserts.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/constants.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/constants.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/errors.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/errors.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/gpaBuilders.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/gpaBuilders.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/helpers.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/helpers.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/models/CandyMachineV2.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/models/CandyMachineV2.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/models/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/models/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/createCandyMachineV2.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/createCandyMachineV2.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/deleteCandyMachineV2.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/deleteCandyMachineV2.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/findCandyMachineV2ByAddress.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/findCandyMachineV2ByAddress.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/findCandyMachinesV2ByPublicKeyField.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/findCandyMachinesV2ByPublicKeyField.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/findMintedNftsByCandyMachineV2.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/findMintedNftsByCandyMachineV2.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/insertItemsToCandyMachineV2.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/insertItemsToCandyMachineV2.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/mintCandyMachineV2.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/mintCandyMachineV2.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/updateCandyMachineV2.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/operations/updateCandyMachineV2.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/pdas.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/pdas.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/program.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/candyMachineV2Module/program.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/corePlugins/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/corePlugins/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/corePlugins/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/corePlugins/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/derivedIdentity/DerivedIdentityClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/derivedIdentity/DerivedIdentityClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/derivedIdentity/errors.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/derivedIdentity/errors.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/derivedIdentity/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/derivedIdentity/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/derivedIdentity/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/derivedIdentity/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/guestIdentity/GuestIdentityDriver.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/guestIdentity/GuestIdentityDriver.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/guestIdentity/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/guestIdentity/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/guestIdentity/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/guestIdentity/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/identityModule/IdentityClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/identityModule/IdentityClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/identityModule/IdentityDriver.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/identityModule/IdentityDriver.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/identityModule/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/identityModule/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/identityModule/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/identityModule/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/keypairIdentity/KeypairIdentityDriver.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/keypairIdentity/KeypairIdentityDriver.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/keypairIdentity/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/keypairIdentity/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/keypairIdentity/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/keypairIdentity/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/mockStorage/MockStorageDriver.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/mockStorage/MockStorageDriver.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/mockStorage/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/mockStorage/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/mockStorage/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/mockStorage/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/Authorization.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/Authorization.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/DelegateInput.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/DelegateInput.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/DelegateType.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/DelegateType.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/NftBuildersClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/NftClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/NftPdasClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/NftPdasClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/accounts.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/accounts.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/errors.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/errors.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/gpaBuilders.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/gpaBuilders.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/helpers.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/helpers.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/models/JsonMetadata.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/models/JsonMetadata.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/models/Metadata.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/models/Metadata.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/models/Nft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/models/Nft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/models/NftEdition.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/models/NftEdition.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/models/Sft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/models/Sft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/models/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/models/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/approveNftCollectionAuthority.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/approveNftCollectionAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/approveNftDelegate.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/approveNftDelegate.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/approveNftUseAuthority.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/approveNftUseAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/createCompressedNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/createCompressedNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/createNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/createNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/createSft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/createSft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/deleteNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/deleteNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftByAssetId.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftByAssetId.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftByMetadata.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftByMetadata.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftByMint.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftByMint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftByToken.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftByToken.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftsByCreator.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftsByCreator.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftsByMintList.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftsByMintList.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftsByOwner.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftsByOwner.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftsByUpdateAuthority.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/findNftsByUpdateAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/freezeDelegatedNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/freezeDelegatedNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/loadMetadata.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/loadMetadata.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/lockNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/lockNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/migrateToSizedCollectionNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/migrateToSizedCollectionNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/mintNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/mintNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/printNewEdition.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/printNewEdition.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/revokeNftCollectionAuthority.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/revokeNftCollectionAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/revokeNftDelegate.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/revokeNftDelegate.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/revokeNftUseAuthority.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/revokeNftUseAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/thawDelegatedNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/thawDelegatedNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/transferCompressedNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/transferCompressedNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/transferNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/transferNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/unlockNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/unlockNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/unverifyNftCollection.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/unverifyNftCollection.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/unverifyNftCreator.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/unverifyNftCreator.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/updateNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/updateNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/uploadMetadata.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/uploadMetadata.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/useNft.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/useNft.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/verifyNftCollection.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/verifyNftCollection.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/operations/verifyNftCreator.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/operations/verifyNftCreator.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/pdas.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/pdas.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/nftModule/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/nftModule/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/operationModule/OperationClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/operationModule/OperationClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/operationModule/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/operationModule/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/operationModule/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/operationModule/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/programModule/ProgramClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/programModule/ProgramClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/programModule/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/programModule/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/programModule/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/programModule/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/rpcModule/RpcClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/rpcModule/RpcClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/rpcModule/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/rpcModule/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/rpcModule/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/rpcModule/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/storageModule/MetaplexFile.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/storageModule/MetaplexFile.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/storageModule/StorageClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/storageModule/StorageClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/storageModule/StorageDriver.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/storageModule/StorageDriver.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/storageModule/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/storageModule/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/storageModule/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/storageModule/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/systemModule/SystemBuildersClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/systemModule/SystemBuildersClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/systemModule/SystemClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/systemModule/SystemClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/systemModule/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/systemModule/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/systemModule/operations/createAccount.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/systemModule/operations/createAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/systemModule/operations/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/systemModule/operations/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/systemModule/operations/transferSol.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/systemModule/operations/transferSol.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/systemModule/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/systemModule/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/TokenBuildersClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/TokenClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/TokenPdasClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/TokenPdasClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/accounts.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/accounts.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/constants.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/constants.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/errors.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/errors.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/gpaBuilders.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/gpaBuilders.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/models/Mint.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/models/Mint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/models/Token.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/models/Token.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/models/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/models/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/approveTokenDelegateAuthority.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/approveTokenDelegateAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/createMint.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/createMint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/createToken.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/createToken.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/createTokenWithMint.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/createTokenWithMint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/findMintByAddress.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/findMintByAddress.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/findTokenByAddress.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/findTokenByAddress.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/findTokenWithMintByAddress.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/findTokenWithMintByAddress.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/findTokenWithMintByMint.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/findTokenWithMintByMint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/freezeTokens.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/freezeTokens.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/mintTokens.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/mintTokens.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/revokeTokenDelegateAuthority.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/revokeTokenDelegateAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/sendTokens.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/sendTokens.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/operations/thawTokens.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/operations/thawTokens.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/tokenModule/program.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/tokenModule/program.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/utilsModule/UtilsClient.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/utilsModule/UtilsClient.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/utilsModule/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/utilsModule/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/utilsModule/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/utilsModule/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/walletAdapterIdentity/WalletAdapterIdentityDriver.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/walletAdapterIdentity/WalletAdapterIdentityDriver.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/walletAdapterIdentity/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/walletAdapterIdentity/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/plugins/walletAdapterIdentity/plugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/plugins/walletAdapterIdentity/plugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/Account.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/Account.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/Amount.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/Amount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/BigNumber.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/BigNumber.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/Cluster.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/Cluster.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/Creator.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/Creator.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/DateTime.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/DateTime.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/FeatureFlags.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/FeatureFlags.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/HasDriver.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/HasDriver.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/HasMetaplex.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/HasMetaplex.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/MetaplexPlugin.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/MetaplexPlugin.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/Model.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/Model.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/Operation.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/Operation.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/Pda.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/Pda.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/Program.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/Program.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/PublicKey.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/PublicKey.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/ReadApi.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/ReadApi.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/Serializer.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/Serializer.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/Signer.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/Signer.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/types/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/types/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/Disposable.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/Disposable.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/GmaBuilder.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/GmaBuilder.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/GpaBuilder.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/GpaBuilder.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/Task.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/Task.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/TransactionBuilder.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/TransactionBuilder.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/assert.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/assert.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/common.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/common.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/exports.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/exports.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/index.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/log.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/log.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/merkle.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/merkle.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/readApiConnection.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/readApiConnection.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    addIndex(
      require("/node_modules/@metaplex-foundation/js/dist/types/utils/types.d.ts")
    ),
    "node_modules/metaplex-foundation/js/dist/types/utils/types.d.ts"
  );

  // Renaming exports allows us to use '@' and export everything
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    `declare module "@metaplex-foundation/js" {
  export * from "node_modules/metaplex-foundation/js/dist/types/old-index"
}`,
    "node_modules/metaplex-foundation/js/dist/types/index.d.ts"
  );
  /* ------------------ End @metaplex-foundation/js ------------------ */
};

/**
 * Monaco TS worker is not able to use Metaplex imports/exports if indexes are
 * not explicit, e.g. "./common" will not translate into "./common/index.d.ts".
 *
 * @param content declaration file content
 * @returns the content with "/index" appended to the necessary imports/exports
 */
const addIndex = (content: string) => {
  return content.replace(/[import|export].*from\s(.+)+/gm, (match, path) => {
    if (path.slice(1).startsWith(".")) {
      // Return the same if the import/export last name starts with an upper case
      // e.g. "../NftClient" should return the same without appending "/index"
      const lastName = path.split("/").pop();
      if (lastName[0] === lastName[0].toUpperCase()) {
        return match;
      }

      const pathWithIndex = match.replace(
        path,
        path.slice(0, path.length - 2) + "/index" + path.slice(path.length - 2)
      );

      if (match.startsWith("import")) {
        return pathWithIndex;
      }

      // Export should include both just in case
      return match + "\n" + pathWithIndex;
    }

    return match;
  });
};
