import * as monaco from "monaco-editor";

export const loadSplTokenTypes = () => {
  /* ------------------ Begin @solana/spl-token ------------------ */
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/index.d.ts"),
    "node_modules/solana/spl-token/lib/types/old-index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/amountToUiAmount.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/amountToUiAmount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/approve.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/approve.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/approveChecked.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/approveChecked.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/burn.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/burn.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/burnChecked.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/burnChecked.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/closeAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/closeAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/createAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/createAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/createAssociatedTokenAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/createAssociatedTokenAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/createMint.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/createMint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/createMultisig.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/createMultisig.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/createNativeMint.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/createNativeMint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/createWrappedNativeAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/createWrappedNativeAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/freezeAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/freezeAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/getOrCreateAssociatedTokenAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/getOrCreateAssociatedTokenAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/index.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/internal.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/internal.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/mintTo.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/mintTo.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/mintToChecked.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/mintToChecked.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/revoke.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/revoke.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/setAuthority.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/setAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/syncNative.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/syncNative.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/thawAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/thawAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/transfer.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/transfer.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/transferChecked.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/transferChecked.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/actions/uiAmountToAmount.d.ts"),
    "node_modules/solana/spl-token/lib/types/actions/uiAmountToAmount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/constants.d.ts"),
    "node_modules/solana/spl-token/lib/types/constants.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/errors.d.ts"),
    "node_modules/solana/spl-token/lib/types/errors.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/accountType.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/accountType.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/defaultAccountState/actions.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/defaultAccountState/actions.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/defaultAccountState/index.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/defaultAccountState/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/defaultAccountState/instructions.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/defaultAccountState/instructions.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/defaultAccountState/state.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/defaultAccountState/state.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/extensionType.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/extensionType.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/immutableOwner.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/immutableOwner.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/index.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/interestBearingMint/actions.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/interestBearingMint/actions.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/interestBearingMint/index.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/interestBearingMint/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/interestBearingMint/instructions.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/interestBearingMint/instructions.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/interestBearingMint/state.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/interestBearingMint/state.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/memoTransfer/actions.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/memoTransfer/actions.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/memoTransfer/index.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/memoTransfer/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/memoTransfer/instructions.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/memoTransfer/instructions.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/memoTransfer/state.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/memoTransfer/state.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/mintCloseAuthority.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/mintCloseAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/nonTransferable.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/nonTransferable.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/transferFee/actions.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/transferFee/actions.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/transferFee/index.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/transferFee/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/transferFee/instructions.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/transferFee/instructions.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/extensions/transferFee/state.d.ts"),
    "node_modules/solana/spl-token/lib/types/extensions/transferFee/state.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/amountToUiAmount.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/amountToUiAmount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/approve.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/approve.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/approveChecked.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/approveChecked.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/associatedTokenAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/associatedTokenAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/burn.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/burn.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/burnChecked.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/burnChecked.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/closeAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/closeAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/createNativeMint.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/createNativeMint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/decode.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/decode.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/freezeAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/freezeAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/index.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/initializeAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/initializeAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/initializeAccount2.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/initializeAccount2.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/initializeAccount3.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/initializeAccount3.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/initializeImmutableOwner.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/initializeImmutableOwner.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/initializeMint.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/initializeMint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/initializeMint2.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/initializeMint2.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/initializeMintCloseAuthority.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/initializeMintCloseAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/initializeMultisig.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/initializeMultisig.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/initializeMultisig2.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/initializeMultisig2.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/initializeNonTransferableMint.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/initializeNonTransferableMint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/internal.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/internal.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/mintTo.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/mintTo.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/mintToChecked.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/mintToChecked.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/reallocate.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/reallocate.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/revoke.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/revoke.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/setAuthority.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/setAuthority.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/syncNative.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/syncNative.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/thawAccount.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/thawAccount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/transfer.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/transfer.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/transferChecked.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/transferChecked.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/types.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/types.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/instructions/uiAmountToAmount.d.ts"),
    "node_modules/solana/spl-token/lib/types/instructions/uiAmountToAmount.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/state/account.d.ts"),
    "node_modules/solana/spl-token/lib/types/state/account.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/state/index.d.ts"),
    "node_modules/solana/spl-token/lib/types/state/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/state/mint.d.ts"),
    "node_modules/solana/spl-token/lib/types/state/mint.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@solana/spl-token/lib/types/state/multisig.d.ts"),
    "node_modules/solana/spl-token/lib/types/state/multisig.d.ts"
  );

  // Renaming exports allows us to use '@' and export everything
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    `declare module "@solana/spl-token" {
  export * from "node_modules/solana/spl-token/lib/types/old-index"
}`,
    "node_modules/solana/spl-token/lib/types/index.d.ts"
  );
  /* ------------------ End @solana/spl-token ------------------ */
};
