ARG USER=solpg
ARG BIN="build-program"

FROM ubuntu:24.04@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab AS base

# Install build deps
ARG DEBIAN_FRONTEND="noninteractive"
RUN apt-get update -qq && apt-get upgrade -qq && apt-get install -qq \
    build-essential curl pkg-config libssl-dev libudev-dev

# Create a non-root user
ARG USER
RUN useradd -m -u 1001 -s /bin/bash ${USER}
USER ${USER}
ENV HOME="/home/${USER}"
WORKDIR ${HOME}

# Install Rust
RUN sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs)" -- -y
ENV PATH="${HOME}/.cargo/bin:${PATH}"

FROM base AS binary

# Cache toolchain
COPY rust-toolchain.toml .
RUN cargo --version

# Cache deps
COPY Cargo.* .
RUN mkdir src
RUN echo "fn main() {}" > src/main.rs
RUN cargo build --release

# Actual build
ARG BIN
COPY src src
RUN cargo build --release --bin ${BIN} --features unstable

FROM base AS final

# Install Solana
ARG SOLANA_VERSION
RUN sh -c "$(curl -sSfL https://release.anza.xyz/v${SOLANA_VERSION}/install)"
ENV PATH="${HOME}/.local/share/solana/install/active_release/bin:${PATH}"

# Run the installation command
ARG INSTALLATION_COMMAND
RUN sh -c "${INSTALLATION_COMMAND}"

# Switch Rust version
ARG RUST_VERSION
RUN rustup default ${RUST_VERSION}

# Copy the contents of the template directory
ARG USER
ARG TEMPLATE
COPY --chown=${USER}:${USER} templates/${TEMPLATE}/ .

# Build the default program to cache
ARG INITIAL_BUILD_COMMAND
RUN sh -c "${INITIAL_BUILD_COMMAND}"

# Remove the binary and IDL directories for clean start
ARG BINARY_PATH
ARG IDL_PATH
RUN rm -rf ${BINARY_PATH} ${IDL_PATH}

# Copy the built binary
ARG BIN
COPY --from=binary ${HOME}/target/release/${BIN} /usr/local/bin/
