ARG USER=solpg
ARG BIN="bundle"

FROM node:22.20.0@sha256:c190e697545bdb4fb32b29c0f47bf742f3c3d974965b825f1437aa127ee7b866 AS base

# Create a non-root user
ARG USER
RUN useradd -m -u 1001 -s /bin/bash ${USER}
USER ${USER}
ENV HOME="/home/${USER}"
WORKDIR ${HOME}

FROM base AS binary

# Install Rust
RUN sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs)" -- -y
ENV PATH="${HOME}/.cargo/bin:${PATH}"

# Cache toolchain
COPY rust-toolchain.toml .
RUN cargo --version

# Cache deps
COPY Cargo.* .
RUN mkdir src
RUN echo "fn main() {}" > src/main.rs
RUN cargo build --release

# Actual build
ARG BIN
COPY src src
RUN cargo build --release --bin ${BIN} --features unstable

FROM base AS final

ARG USER
ARG PACKAGES_DIR="packages"

# Copy files
COPY --chown=${USER}:${USER} ${PACKAGES_DIR} ${PACKAGES_DIR}

# Disable self-update checks.
#
# ```
# Performing "GET" request to "https://yarnpkg.com/latest-version".
# There appears to be trouble with your network connection. Retrying...
# ```
RUN yarn config set disable-self-update-check true

# Install polyfill deps
RUN yarn --ignore-scripts --cwd packages/polyfills

# Make `webpack` available globally
ENV PATH="${HOME}/${PACKAGES_DIR}/polyfills/node_modules/.bin:${PATH}"

# Temporarily pre-install deps to avoid excessive installations during development
# TODO: Remove
ARG TEMPLATE_DIR="templates/legacy"
COPY --chown=${USER}:${USER} ${TEMPLATE_DIR}/package.json ${TEMPLATE_DIR}/yarn.lock packages/
RUN yarn --ignore-scripts --cwd packages

# Copy the built binary
ARG BIN
COPY --from=binary ${HOME}/target/release/${BIN} /usr/local/bin/
