ARG USER=solpg

FROM node:22.20.0@sha256:c190e697545bdb4fb32b29c0f47bf742f3c3d974965b825f1437aa127ee7b866 AS base

# Create a non-root user
ARG USER
RUN useradd -m -u 1001 -s /bin/bash ${USER}
USER ${USER}
ENV HOME="/home/${USER}"
WORKDIR ${HOME}

FROM base AS binary

# Install Rust
RUN sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs)" -- -y
ENV PATH="${HOME}/.cargo/bin:${PATH}"

# Cache toolchain
COPY rust-toolchain.toml .
RUN cargo --version

# Cache deps
COPY Cargo.* .
RUN mkdir src
RUN echo "fn main() {}" > src/main.rs
RUN cargo build --release

# Actual build
COPY src src
RUN cargo build --release --bin bundle --features unstable

FROM base AS final

ARG USER

# Copy files
COPY --chown=${USER}:${USER} packages packages

# Install dependencies
# TODO: Remove and install in process
RUN yarn --ignore-scripts --cwd packages

# Copy the built binary
COPY --from=binary ${HOME}/target/release/bundle /usr/local/bin/
