ARG USER=solpg
ARG SOLANA_VERSION="1.17.34"

FROM ubuntu:24.04@sha256:80dd3c3b9c6cecb9f1667e9290b3bc61b78c2678c02cbdae5f0fea92cc6734ab AS base

# Install build deps
ARG DEBIAN_FRONTEND="noninteractive"
RUN apt-get update -qq && apt-get upgrade -qq && apt-get install -qq \
    build-essential curl pkg-config libssl-dev libudev-dev

# Create a non-root user
ARG USER
RUN useradd -m -u 1001 -s /bin/bash ${USER}
USER ${USER}
ENV HOME="/home/${USER}"
WORKDIR ${HOME}

# Install Rust
RUN sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs)" -- -y
ENV PATH="${HOME}/.cargo/bin:${PATH}"

FROM base AS binary

# Cache toolchain
COPY rust-toolchain.toml .
RUN cargo --version

# Cache deps
COPY Cargo.* .
RUN mkdir src
RUN echo "fn main() {}" > src/main.rs
RUN cargo build --release

# Actual build
COPY src src
RUN cargo build --release --bin build-program --features unstable

FROM base AS final

ARG USER
ARG SOLANA_VERSION

# Install Solana
RUN sh -c "$(curl -sSfL https://release.anza.xyz/v${SOLANA_VERSION}/install)"
ENV PATH="${HOME}/.local/share/solana/install/active_release/bin:${PATH}"

# Copy programs dir and build the default program
COPY --chown=${USER}:${USER} programs programs
RUN cargo-build-sbf --manifest-path programs/Cargo.toml

# Copy the built binary
COPY --from=binary ${HOME}/target/release/build-program /usr/local/bin/
