import * as monaco from "monaco-editor";

export default function declareAnchor() {
  /* ------------------ Begin @project-serum/anchor ------------------ */
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/index.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/old-index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/borsh/accounts.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/borsh/accounts.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/borsh/event.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/borsh/event.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/borsh/idl.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/borsh/idl.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/borsh/index.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/borsh/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/borsh/instruction.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/borsh/instruction.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/borsh/state.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/borsh/state.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/common.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/common.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/index.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/spl-token/accounts.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/spl-token/accounts.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/spl-token/buffer-layout.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/spl-token/buffer-layout.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/spl-token/events.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/spl-token/events.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/spl-token/index.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/spl-token/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/spl-token/instruction.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/spl-token/instruction.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/coder/spl-token/state.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/coder/spl-token/state.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/error.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/error.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/idl.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/idl.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/nodewallet.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/nodewallet.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/accounts-resolver.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/accounts-resolver.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/common.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/common.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/context.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/context.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/event.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/event.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/index.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/namespace/account.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/namespace/account.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/namespace/index.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/namespace/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/namespace/instruction.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/namespace/instruction.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/namespace/methods.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/namespace/methods.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/namespace/rpc.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/namespace/rpc.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/namespace/simulate.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/namespace/simulate.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/namespace/state.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/namespace/state.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/namespace/transaction.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/namespace/transaction.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/program/namespace/types.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/program/namespace/types.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/provider.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/provider.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/spl/index.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/spl/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/spl/token.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/spl/token.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/bytes/base64.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/bytes/base64.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/bytes/bs58.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/bytes/bs58.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/bytes/hex.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/bytes/hex.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/bytes/index.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/bytes/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/bytes/utf8.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/bytes/utf8.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/common.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/common.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/features.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/features.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/index.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/index.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/pubkey.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/pubkey.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/registry.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/registry.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/rpc.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/rpc.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/sha256.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/sha256.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/utils/token.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/utils/token.d.ts"
  );
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    require("/node_modules/@project-serum/anchor/dist/browser/types/src/workspace.d.ts"),
    "node_modules/project-serum/anchor/dist/browser/types/src/workspace.d.ts"
  );

  // Renaming exports allows us to use '@' and export everything
  monaco.languages.typescript.typescriptDefaults.addExtraLib(
    `declare module "@project-serum/anchor" {
  export * from "node_modules/project-serum/anchor/dist/browser/types/src/old-index"
}`,
    "node_modules/project-serum/anchor/dist/browser/types/src/index.d.ts"
  );
  /* ------------------ End @project-serum/anchor ------------------ */
}
